### ISSUE TITLE
Козин Георгий (ШNG_C-_Sun)

### ISSUE THREAD

**Issue by stormtrooper66-exe** [vlasove/ING_C-_Sun#4]
https://github.com/stormtrooper66-exe/dark_side-ING_C-_Sun/tree/master/д:з%202

**Comment by vlasove** [comment]
task1 --- неверное решение. У тебя есть функция перевода из **UTF8** в **unicode** . Ею надо воспользоваться, а не просто держать ее объявление в файле)

**Comment by vlasove** [comment]
task2 --- зачтено

**Comment by vlasove** [comment]
task3 --- неверное решение. Попробуй более детально проанализировать задачу :)

**Comment by vlasove** [comment]
task4 --- зачтено

**Comment by stormtrooper66-exe** [comment]
так, значит task3 и task1 остались

**Comment by stormtrooper66-exe** [comment]
а как тогда воспользоваться функцией в task1? простите что туплю :(

**Comment by stormtrooper66-exe** [comment]
я исправил task 3

**Comment by vlasove** [comment]
task1 --- зачтено

**Comment by vlasove** [comment]
task3 --- зачтено

**Comment by vlasove** [comment]
Красавчик!


**Зачет по ДЗ!**

**Comment by stormtrooper66-exe** [comment]
зачат по д/з? Урааааааааааа! Последний раз когда я так радовался, был в июне, когда я получил высшие балы по ОГЭ! Ураааааааааааааа!
