### ISSUE TITLE
Module_1

### ISSUE THREAD

**Issue by GluKhovKirill** [vlasove/ING_C-_Sun#6]
_Модульный проект 1
Автор: Глухов К. А._
[main.txt](https://github.com/vlasove/ING_C-_Sun/files/3783433/main.txt)

**Comment by vlasove** [comment]
Скинь плиз в виде ```.py``` файла , а не ```.txt```

**Comment by GluKhovKirill** [comment]
Гит .cpp не поддерживает

[main.zip](https://github.com/vlasove/ING_C-_Sun/files/3827706/main.zip)

**Comment by GluKhovKirill** [comment]
@vlasove надеюсь, это тебя призовет

**Comment by vlasove** [comment]
Супер) На будущее - по константым ссылкам параметры в функции передавать нужно очень аккуратно. В данном случае это не ошибка, но если я отстегну функцию - она умрет

**Comment by vlasove** [comment]
Зачет по модулю!
